version: 0.4.3

############################
## Author
############################

author:
  name: Vasyl
  full_name: Vasyl Posmit
  # introduction: I am Vasyl
  image: avatar.jpeg
  # image: avatar_2021.jpg

  greeting: "Explore my works and reach me out :pray:"
  # icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/VasylPosmit
  - linkedin: https://www.linkedin.com/in/posmit/
  - telegram:  https://t.me/posmit
  - email: mailto:vasyl.posmit@gmail.com
  # - link: https://github.com/VasylPosmit/vp#readme
  # - website: 
  - x-twitter: https://x.com/posmit
  # - mastodon: 
  # - instagram: 
  # - reddit: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: paramsVasyl
description: "Vasyl Posmit personal site"
images:
  - thumbnail.png
